import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { calculateFinance } from "../../../shared/finance";
import { Calculator, TrendingDown, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";

const rupiah = new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 });
export function CalculatorPage() { const [income, setIncome] = useState("0"); const [capital, setCapital] = useState("0"); const [expense, setExpense] = useState("0"); const calculation = calculateFinance(Number(income), Number(capital), Number(expense)); const total = calculation.net; const isProfit = calculation.status === "untung"; return <div className="space-y-7"><section className="page-heading"><p className="eyebrow">CALCULATOR</p><h2>Perhitungan Finansial</h2><p>Hitung hasil bersih setelah modal dan pengeluaran operasional.</p></section><div className="grid gap-5 lg:grid-cols-[.95fr_1.05fr]"><Card className="surface-card"><CardContent className="p-6"><div className="mb-6 flex items-center gap-3"><div className="metric-icon purple"><Calculator /></div><div><h3 className="font-black text-white">Masukkan Nilai</h3><p className="text-sm text-slate-400">Seluruh nilai dalam Rupiah.</p></div></div><div className="space-y-4"><CalculatorField label="Total Pendapatan" value={income} onChange={setIncome} /><CalculatorField label="Modal" value={capital} onChange={setCapital} /><CalculatorField label="Pengeluaran" value={expense} onChange={setExpense} /></div></CardContent></Card><Card className={`calculator-result ${isProfit ? "profit" : "loss"}`}><CardContent className="flex h-full flex-col justify-between p-7"><div><p className="eyebrow">HASIL BERSIH</p><h3 className="mt-3 text-4xl font-black text-white">{rupiah.format(total)}</h3><div className="mt-5 inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-black"><span className={`status-dot ${isProfit ? "green" : "red"}`} />{isProfit ? "UNTUNG" : "RUGI"}</div></div><div className="mt-10 grid grid-cols-3 gap-2 text-center"><ResultPart label="Pendapatan" value={income} /><ResultPart label="Modal" value={capital} /><ResultPart label="Pengeluaran" value={expense} /></div><p className="mt-5 text-xs leading-5 text-slate-400">Formula: Total Pendapatan − Modal − Pengeluaran = Hasil Bersih.</p></CardContent></Card></div></div>; }
function CalculatorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <div className="space-y-2"><Label className="text-sm text-slate-300">{label}</Label><div className="money-input"><span>Rp</span><Input type="number" min="0" value={value} onChange={(e) => onChange(e.target.value)} /></div></div>; }
function ResultPart({ label, value }: { label: string; value: string }) { return <div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-500">{label}</p><strong className="mt-1 block text-xs text-white">{rupiah.format(Number(value))}</strong></div>; }
