import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Music2, Pause, Play, Search, SkipBack, Volume2 } from "lucide-react";
import { FormEvent, useEffect, useRef, useState } from "react";
import { toast } from "sonner";

type Track = { id: string | number; title: string; artist: string; album: string; artworkUrl: string; previewUrl: string };

function DigitalMoment() {
  const [now, setNow] = useState(() => new Date());
  useEffect(() => { const interval = window.setInterval(() => setNow(new Date()), 1000); return () => window.clearInterval(interval); }, []);
  return <><div className="w-[70px] shrink-0 rounded-lg border border-violet-300/15 bg-white/[0.035] px-1.5 py-1 text-center lg:hidden"><p className="font-mono text-[11px] font-black tracking-[0.08em] text-violet-100">{now.toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" })}</p><p className="mt-0.5 text-[8px] font-bold uppercase tracking-[0.06em] text-slate-400">{now.toLocaleDateString("id-ID", { day: "2-digit", month: "short", year: "numeric" })}</p></div><div className="hidden rounded-xl border border-violet-300/15 bg-white/[0.035] px-3 py-1.5 text-right lg:block"><p className="font-mono text-base font-black tracking-[0.14em] text-violet-100">{now.toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</p><p className="mt-0.5 text-[9px] font-bold uppercase tracking-[0.17em] text-slate-400">{now.toLocaleDateString("id-ID", { weekday: "short", day: "2-digit", month: "short", year: "numeric" })}</p></div></>;
}

function MusicDesk({ sessionToken }: { sessionToken: string }) {
  const [open, setOpen] = useState(false); const [term, setTerm] = useState(""); const [submitted, setSubmitted] = useState(""); const [track, setTrack] = useState<Track | null>(null); const [playing, setPlaying] = useState(false); const audio = useRef<HTMLAudioElement | null>(null);
  const search = trpc.dashboard.searchMusic.useQuery({ sessionToken, query: submitted || "musik" }, { enabled: false, retry: 1 });
  useEffect(() => () => { audio.current?.pause(); }, []);
  const selectTrack = (item: Track) => { audio.current?.pause(); const player = new Audio(item.previewUrl); audio.current = player; player.volume = 0.75; player.onended = () => setPlaying(false); player.play().then(() => setPlaying(true)).catch(() => toast.error("Pratinjau tidak dapat diputar di perangkat ini.")); setTrack(item); };
  const toggle = () => { if (!audio.current) return; if (audio.current.paused) { audio.current.play().then(() => setPlaying(true)); } else { audio.current.pause(); setPlaying(false); } };
  const submit = (event: FormEvent) => { event.preventDefault(); if (term.trim().length < 2) return toast.error("Masukkan minimal 2 karakter."); setSubmitted(term.trim()); setTimeout(() => search.refetch(), 0); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="icon" variant="ghost" className="text-violet-200 hover:bg-violet-500/10 hover:text-white" aria-label="Cari musik"><Music2 className="h-5 w-5" /></Button></DialogTrigger><DialogContent className="dialog-dark max-h-[85vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle className="flex items-center gap-2"><Music2 className="h-5 w-5 text-violet-300" />Music Desk</DialogTitle></DialogHeader><p className="text-sm text-slate-400">Cari lagu dan dengarkan pratinjau resmi sambil bekerja.</p><form onSubmit={submit} className="flex gap-2"><Input value={term} onChange={(event) => setTerm(event.target.value)} placeholder="Cari judul lagu atau artis..." /><Button type="submit" className="primary-action" disabled={search.isFetching}><Search />Cari</Button></form>{track && <div className="flex items-center gap-3 rounded-xl border border-violet-300/15 bg-violet-500/10 p-3"><img src={track.artworkUrl} alt="" className="h-12 w-12 rounded-lg object-cover" /><div className="min-w-0 flex-1"><strong className="block truncate text-sm text-white">{track.title}</strong><p className="truncate text-xs text-slate-400">{track.artist}</p></div><Button size="icon" variant="outline" onClick={toggle} aria-label="Putar atau jeda">{playing ? <Pause /> : <Play />}</Button><Button size="icon" variant="ghost" onClick={() => { audio.current?.pause(); setPlaying(false); setTrack(null); }} aria-label="Hentikan"><SkipBack /></Button></div>}<div className="space-y-2">{search.isFetching && <p className="py-5 text-center text-sm text-violet-200">Mencari musik...</p>}{search.error && <p className="rounded-lg bg-rose-500/10 p-3 text-sm text-rose-200">{search.error.message}</p>}{(search.data ?? []).map((item) => <button key={item.id} onClick={() => selectTrack(item)} className="flex w-full items-center gap-3 rounded-xl border border-white/5 bg-white/[0.025] p-2.5 text-left transition hover:border-violet-300/25 hover:bg-violet-500/10"><img src={item.artworkUrl} alt="" className="h-11 w-11 rounded-md object-cover" /><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-white">{item.title}</strong><span className="block truncate text-xs text-slate-400">{item.artist}{item.album ? ` · ${item.album}` : ""}</span></span><Play className="h-4 w-4 text-violet-300" /></button>)}{submitted && !search.isFetching && !(search.data ?? []).length && <p className="py-5 text-center text-sm text-slate-400">Tidak ada pratinjau yang ditemukan.</p>}</div><p className="flex items-center gap-2 text-[11px] text-slate-500"><Volume2 className="h-3.5 w-3.5" />Pemutaran berupa pratinjau musik resmi.</p></DialogContent></Dialog>;
}

export function WorkspaceTools({ sessionToken }: { sessionToken: string }) { return <div className="ml-auto flex items-center gap-1.5"><DigitalMoment /><MusicDesk sessionToken={sessionToken} /></div>; }
